version: '3.4'

services:
    app:
        image: node:18.0
        working_dir: '/usr/src/app'
        command: bash -c 'npm i && npm run dev'
        ports:
            - '5173:5173'
        volumes:
            - '.:/usr/src/app:z'
